Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;


namespace WEB_ProyectoFinal_Grupo3.Models
{
    public class Categoria
    {
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El nombre debe tener entre 3 y 50 caracteres.")]
        public required string Nombre { get; set; }

        [Required(ErrorMessage = "La descripción es obligatoria")]
        [Display(Name = "Descripcion")]
        public required string Descripcion { get; set; }

        [NotMapped] // Esta propiedad no se mapeará a la base de datos
        [Display(Name = "Imagen de la Categoría")]
        public IFormFile? ImagenArchivo { get; set; }

        [Display(Name = "Ruta Imagen")]
        public string? ImagenCategoriaPath { get; set; }
    }
}

Models/Paquete.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WEB_ProyectoFinal_Grupo3.Models
{
    public class Paquete
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El nombre debe tener entre 3 y 50 caracteres.")]
        public required string Nombre { get; set; }

        [Required(ErrorMessage = "La descripción es obligatoria.")]
        public required string Descripcion { get; set; }

        [Required(ErrorMessage = "El costo es obligatorio.")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "El costo debe tener hasta dos decimales.")]
        [Range(0, 1000000, ErrorMessage = "El costo debe estar entre 0 y 1,000,000.")]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        public required decimal Costo { get; set; }

        [Required(ErrorMessage = "La duración es obligatoria.")]
        [Range(1, 44640, ErrorMessage = "La duración debe estar entre 1 y 44,640 minutos (1 mes).")]
        public int Duracion { get; set; }


        [Required]
        public required EstadosPaquetes Estado { get; set; } = EstadosPaquetes.Disponible;


        [NotMapped] // Esta propiedad no se mapeará a la base de datos
        [Display(Name = "Imagen del Paquete")]
        public IFormFile? ImagenArchivo { get; set; }

        [Display(Name = "Ruta Imagen")]
        public string? ImagenPaquetePath { get; set; }

        [Required]
        [ForeignKey("Categoria")]
        public required int IdCategoria { get; set; }



        public Categoria? Categoria { get; set; 
}

    }
}

Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WEB_ProyectoFinal_Grupo3.Data;
using WEB_ProyectoFinal_Grupo3.Models;
using System.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.StaticFiles;
using NuGet.Packaging.Signing;
using System.Drawing;
using Microsoft.EntityFrameworkCore.ChangeTracking;


namespace WEB_ProyectoFinal_Grupo3.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly DBContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;



        public CategoriasController(DBContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
              return _context.Categorias != null ? 
                          View(await _context.Categorias.ToListAsync()) :
                          Problem("Entity set 'DBContext.Categorias'  is null.");
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,ImagenArchivo")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Verificar si la carpeta de imágenes de categorías existe, de lo contrario, crearla
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "img/Categorias");
                    if (!Directory.Exists(imagePath))
                    {
                        Directory.CreateDirectory(imagePath);
                    }

                    // Lógica para guardar la imagen de la categoría, si es necesario
                    if (categoria.ImagenArchivo != null)
                    {
                        // Obtener la extensión del archivo
                        string extension = Path.GetExtension(categoria.ImagenArchivo.FileName);

                        // Verificar si la extensión es jpg, png o jpeg
                        if (extension != ".jpg" && extension != ".png" && extension != ".jpeg")
                        {
                            TempData["Error"] = "Solo se permiten imágenes con extensiones jpg, png o jpeg.";
                            return View(categoria);
                        }

                        // Obtener el nombre de archivo único
                        string uniqueFileName = Guid.NewGuid().ToString() + extension;
                        string filePath = Path.Combine(imagePath, uniqueFileName);

                        try
                        {
                            // Guardar el archivo en el servidor


                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await categoria.ImagenArchivo.CopyToAsync(stream);
                            }
                        }
                        catch (Exception ex)
                        {
                            TempData["Error"] = $"No se pudo guardar la imagen de categoría por: {ex.Message}";
                            return View(categoria);
                        }

                        // Asignar la ruta de la imagen al objeto de la categoría
                        categoria.ImagenCategoriaPath = "/img/Categorias/" + uniqueFileName; // Ruta relativa al directorio web
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = $"No se pudo crear la categoría por: {ex.Message}";
                    return View(categoria);
                }

                // Agregar la categoría al contexto y guardar los cambios
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                TempData["Success"] = $"Categoría: {categoria.Nombre}, creada exitosamente!";
                return RedirectToAction(nameof(Index));
            }

            return View(categoria);
        }

     
        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,ImagenArchivo,ImagenCategoriaPath")] Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Verificar si la carpeta de imágenes de categorías existe, de lo contrario, crearla
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "img/Categorias");
                    if (!Directory.Exists(imagePath))
                    {
                        Directory.CreateDirectory(imagePath);
                    }

                    // Si hay una imagen actualmente asociada a la categoría, eliminarla del servidor
                    if (!string.IsNullOrEmpty(categoria.ImagenCategoriaPath))
                    {
                        string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, categoria.ImagenCategoriaPath.TrimStart('/'));

                       

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    // Lógica para guardar la nueva imagen de la categoría, si se proporciona
                    if (categoria.ImagenArchivo != null)
                    {
                        // Obtener la extensión del archivo
                        string extension = Path.GetExtension(categoria.ImagenArchivo.FileName);

                        // Verificar si la extensión es jpg, png o jpeg
                        if (extension != ".jpg" && extension != ".png" && extension != ".jpeg")
                        {
                            TempData["Error"] = "Solo se permiten imágenes con extensiones jpg, png o jpeg.";
                            return View(categoria);
                        }

                        // Obtener el nombre de archivo único
                        string uniqueFileName = Guid.NewGuid().ToString() + extension;
                        string filePath = Path.Combine(imagePath, uniqueFileName);

                        // Guardar el archivo en el servidor
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await categoria.ImagenArchivo.CopyToAsync(stream);
                        }

                        // Asignar la ruta de la nueva imagen al objeto de la categoría
                        categoria.ImagenCategoriaPath = "/img/Categorias/" + uniqueFileName; // Ruta relativa al directorio web
                    }

                    // Actualizar la categoría en el contexto y guardar los cambios
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = $"Categoría: {categoria.Nombre}, actualizada exitosamente!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = $"No se pudo editar la categoría: {ex.Message}";
                    return View(categoria);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }


        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WEB_ProyectoFinal_Grupo3.Data;
using WEB_ProyectoFinal_Grupo3.Models;

namespace WEB_ProyectoFinal_Grupo3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly DBContext _context;


   
        public HomeController(ILogger<HomeController> logger, DBContext context)
        {
            _logger = logger;
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {

            var categorias = await _context.Categorias.ToListAsync(); // Obtener tus categorías de alguna manera
            var paquetes = await _context.Paquetes.ToListAsync(); // Obtener tus paquetes de alguna manera

            var viewModel = new CategoriaPaqueteViewModel
            {
                Categorias =  categorias,
                Paquetes =  paquetes
            };

            return View(viewModel);



          
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Membresias()
        {
            return View();
        }

        public async Task<IActionResult> Paquetes()
        {
            var dBContext = _context.Paquetes.Include(p => p.Categoria);
            return View(await dBContext.ToListAsync());
        }

        public async Task<IActionResult> Categorias()
        {
            var dBContext = _context.Categorias;
            return View(await dBContext.ToListAsync());
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Categorias.cshtml
@model IEnumerable<WEB_ProyectoFinal_Grupo3.Models.Categoria>

@{
    ViewData["Title"] = "Paquetes";
}
@{
    @if (Model.Any())
    {
        <div id="Categorías" class="card pt-1">
            <div class="card-header text-center">
                <h4 class="text-black"><i class="bi bi-tags d-inline-block"></i> Categorías</h4>
            </div>

            <div class="row">
                @foreach (var categoria in Model)
                {
                    <div class="col-md-4">
                        <div class="card">
                            <img src="@categoria.ImagenCategoriaPath" class="card-img-top" alt="@categoria.Nombre">
                            <div class="card-body">
                                <h5 class="card-title">@categoria.Nombre</h5>
                                <p class="card-text">@categoria.Descripcion</p>
                                <div class="text-center">
                                    <a href="@Url.Action("Details", "Categorias", new { id = categoria.Id })" class="btn btn-primary mt-3"><i class="bi bi-eye"></i> Comprar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
}

Views/Home/Index.cshtml
@model WEB_ProyectoFinal_Grupo3.Models.CategoriaPaqueteViewModel

@{
    ViewData["Title"] = "Home Page";
}
@if (Model.Categorias.Any())
{
    <section id="Carrousel">
        <div class="container-fluid">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    @foreach (var item in Model.Categorias)
                    {
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@item.Id" class="@(@item.Id == Model.Categorias.First().Id ? "active" : "")" aria-current="@(@item.Id == Model.Categorias.First().Id ? "true" : "false")" aria-label="Slide @item.Id"></button>
                    }
                </div>

                <div class="carousel-inner">
                    @foreach (var item in Model.Categorias)
                    {
                        <div class="carousel-item @(item.Id == Model.Categorias.First().Id ? "active" : "")">
                            <img src="@item.ImagenCategoriaPath" class="d-block w-100" alt="@item.Nombre">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>@item.Nombre</h5>
                                <p>@item.Descripcion</p>
                            </div>
                        </div>
                    }
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </section>
}
else
{
    <div class="container">
        <div class="alert alert-warning" role="alert">
            No hay categorías disponibles.
        </div>
    </div>
}











<div class="container-fluid mt-1 mb-1" id="QuienesSomos">

    <div class="card-header text-center text-black bg-secondary bg-gradient">
        <h5 class="mb-4">
            <i class="fas fa-search"></i> Explora, <i class="fas fa-smile"></i> Disfruta y <i class="fas fa-heartbeat"></i> Vive al Máximo!
        </h5>
    </div>

    <div class="row mt-2">
        <div class="col-md-6 border-right ">
            <h5><i class="fas fa-users"></i> ¿Quiénes Somos?</h5>
            <div class="text-justify">
                <div class="d-flex justify-content-between">
                    <img src="~/img/img1.png" alt="Logo del Club de Recreación" class="mx-auto d-block" style="max-width: 100px;">
                    <img src="~/img/img2.png" alt="Logo del Club de Recreación" class="mx-auto d-block" style="max-width: 100px;">
                    <img src="~/img/img3.png" alt="Logo del Club de Recreación" class="mx-auto d-block" style="max-width: 100px;">
                </div>
                <p style="text-align: justify;">
                    Nos dedicamos a promover un estilo de vida equilibrado y saludable a través del entretenimiento y la actividad física.
                </p>
                <p style="text-align: justify;">
                    Nuestro equipo está comprometido a proporcionar recursos informativos y experiencias enriquecedoras para que puedas disfrutar al máximo de tu tiempo libre.
                </p>
            </div>
        </div>

        <div class="col-md-6 border-left mb-2">
            <h5><i class="fas fa-cogs"></i> Nuestros Servicios</h5>
            <ul class="text-justify">
                <li class="border-bottom">
                    <strong>Explora Eventos:</strong>
                    <p style="text-align: justify;">
                        Descubre una amplia variedad de eventos locales, desde conciertos y festivales hasta ferias y exposiciones. Mantente al día con nuestro calendario de eventos y no te pierdas ninguna oportunidad de diversión.
                    </p>
                </li>
                <li class="border-bottom">
                    <strong>Encuentra Actividades:</strong>
                    <p style="text-align: justify;">
                        Explora nuestras guías de actividades para encontrar opciones emocionantes que se adapten a tus intereses y necesidades. Ya sea que prefieras deportes al aire libre, arte y cultura, o actividades de relajación, ¡tenemos algo para ti!
                    </p>
                </li>
                <li>
                    <strong>Conéctate con la Comunidad:</strong>
                    <p style="text-align: justify;">
                        Únete a nuestra comunidad en línea y comparte tus experiencias, recomendaciones y fotos. Conéctate con personas que comparten tus intereses y descubre nuevas formas de disfrutar del tiempo libre.
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

@{
    @if (Model.Categorias.Any())
    {
        <div id="Categorías" class="card pt-1">
            <div class="card-header text-center">
                <h4 class="text-black"><i class="bi bi-tags d-inline-block"></i> Categorías</h4>
            </div>

            <div class="row">
                @foreach (var categoria in Model.Categorias)
                {
                    <div class="col-md-4">
                        <div class="card">
                            <img src="@categoria.ImagenCategoriaPath" class="card-img-top" alt="@categoria.Nombre">
                            <div class="card-body">
                                <h5 class="card-title">@categoria.Nombre</h5>
                                <p class="card-text">@categoria.Descripcion</p>
                                <div class="text-center">
                                    <a href="@Url.Action("Details", "Categorias", new { id = categoria.Id })" class="btn btn-primary mt-3"><i class="bi bi-eye"></i> Ver Detalles</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
}

<div id="Membresias" class="card pt-1">
    <h4 class="text-white"><i class="bi bi-people"></i> Membresías</h4>
    <div class="row">

        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-person" style="font-size: 3rem;"></i>
                    <h5 class="card-title mt-3">Membresía Estándar</h5>
                    <p class="card-text">Únete a nuestra membresía estándar y disfruta de beneficios exclusivos.</p>
                    <a href="#membresia_estandar" class="btn btn-primary"><i class="bi bi-eye"></i> Ver Detalles</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-gem" style="font-size: 3rem;"></i>
                    <h5 class="card-title mt-3">Membresía Premium</h5>
                    <p class="card-text">
                        Obtén acceso a contenido premium y descuentos exclusivos con nuestra membresía
                        premium.
                    </p>
                    <a href="#membresia_premium" class="btn btn-primary"><i class="bi bi-eye"></i> Ver Detalles</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body d-flex flex-column align-items-center justify-content-center">
                    <i class="bi bi-star" style="font-size: 3rem;"></i>
                    <h5 class="card-title mt-3">Membresía VIP</h5>
                    <p class="card-text">
                        Experimenta lo mejor de nuestro servicio con la membresía VIP, que incluye
                        beneficios exclusivos y atención personalizada.
                    </p>
                    <a href="#membresia_vip" class="btn btn-primary"><i class="bi bi-eye"></i> Ver Detalles</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Paquetes de Recreación - Aventura -->


@if (Model.Paquetes.Any())
{
        <div id="Paquetes" class="card pt-1">
            <div class="card-header text-center">
            <h4 class="text-black"><i class="bi bi-tags d-inline-block"></i> Paquetes</h4>
        </div>

        <div class="row">
            @foreach (var paquete in Model.Paquetes)
            {
                <div class="col-md-4">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column align-items-center justify-content-center">
                            <strong class="text-muted">Categoria: @paquete.Categoria.Nombre</strong>

                            @if (!string.IsNullOrEmpty(paquete.ImagenPaquetePath))
                            {
                                <img src="@paquete.ImagenPaquetePath" alt="Imagen" class="img-thumbnail" style="max-width: 150px;">

                            }
                            else
                            {
                                <span class="mr-2"><i class="bi bi-image"></i></span>
                            }

                            <h5 class="card-title mt-3">@paquete.Nombre</h5>

                            @{
                                var duracionText = paquete.Duracion > 60 ? (paquete.Duracion / 60 == 1 ? "1 hora" : $"{paquete.Duracion / 60} horas") : $"{paquete.Duracion} minutos";
                            }
                            <small class="text-muted"> Duración: <i class="bi bi-clock"></i> @duracionText</small>

                            <strong class="text-muted"> Costo: RD$@Html.DisplayFor(model => paquete.Costo)</strong>
                            
                            <strong class="text-justify text-dark">@paquete.Descripcion</strong>


                            <a href="@Url.Action("Details", "Paquetes", new { id = paquete.Id })" class="btn btn-primary mt-3"><i class="bi bi-eye"></i> Ver Detalles</a>
                    
                        </div>
                    </div>
                </div>

            }


        </div>
    </div>
}

Views/Home/Membresias.cshtml
@model WEB_ProyectoFinal_Grupo3.Models.CategoriaPaqueteViewModel

@{
    ViewData["Title"] = "Membresias";
}

<div class="container text-center mt-1">
    <h5 class="mb-4">Elige tu membresía</h5>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="my-0 font-weight-normal">Estándar</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">RD$ 1000</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Acceso básico al portal</li>
                        <li>Contenido exclusivo</li>
                        <li>Soporte básico</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-primary">Seleccionar</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="my-0 font-weight-normal">Premium</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">RD$ 2500</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Acceso completo al portal</li>
                        <li>Contenido premium</li>
                        <li>Soporte prioritario</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-primary">Seleccionar</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="my-0 font-weight-normal">VIP</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">RD$ 5000</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Acceso completo al portal</li>
                        <li>Contenido VIP</li>
                        <li>Soporte premium</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-primary">Seleccionar</button>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Paquetes.cshtml
@model IEnumerable<WEB_ProyectoFinal_Grupo3.Models.Paquete>

@{
    ViewData["Title"] = "Paquetes";
}
@if (Model.Any())
{
    <div id="Paquetes" class="card pt-1">
        <div class="card-header text-center">
            <h4 class="text-black"><i class="bi bi-tags d-inline-block"></i> Paquetes</h4>
        </div>

        <div class="row">
            @foreach (var paquete in Model)
            {
                <div class="col-md-4">
                    <div class="card h-100">
                        <div class="card-body d-flex flex-column align-items-center justify-content-center">
                            <strong class="text-muted">Categoria: @paquete.Categoria.Nombre</strong>

                            @if (!string.IsNullOrEmpty(paquete.ImagenPaquetePath))
                            {
                                <img src="@paquete.ImagenPaquetePath" alt="Imagen" class="img-thumbnail" style="max-width: 150px;">

                            }
                            else
                            {
                                <span class="mr-2"><i class="bi bi-image"></i></span>
                            }

                            <h5 class="card-title mt-3">@paquete.Nombre</h5>

                            @{
                                var duracionText = paquete.Duracion > 60 ? (paquete.Duracion / 60 == 1 ? "1 hora" : $"{paquete.Duracion / 60} horas") : $"{paquete.Duracion} minutos";
                            }
                            <small class="text-muted"> Duración: <i class="bi bi-clock"></i> @duracionText</small>

                            <strong class="text-muted"> Costo: RD$@Html.DisplayFor(model => paquete.Costo)</strong>

                            <strong class="text-justify text-dark">@paquete.Descripcion</strong>


                            <a href="@Url.Action("Details", "Paquetes", new { id = paquete.Id })" class="btn btn-primary mt-3"><i class="bi bi-eye"></i> Comprar</a>

                        </div>
                    </div>
                </div>

            }


        </div>
    </div>
}